#!/bin/sh

# call with platform: sudo ./install arm|ubuntu|mac
ARCH=${1:-arm}

mkdir -p /usr/local/opt/rhbuilder && cd /usr/local/opt/rhbuilder
wget https://raw.githubusercontent.com/goliatone/rabbithook-builder/master/conf/init.d/rhbuilder.tpl -O .rhbuilder
chmod 755 /usr/local/opt/rhbuilder/.rhbuilder

cd /usr/local/opt/rhbuilder
wget https://raw.githubusercontent.com/goliatone/rabbithook-builder/master/conf/init.d/rhbuilder-launcher -O launcher

cd /usr/local/bin/
wget https://raw.githubusercontent.com/goliatone/rabbithook-builder/master/bin/$ARCH/rhbuilder


echo "cd into init.d"
cd /etc/init.d
echo "Downloading rhbuilder init.d job"
wget https://raw.githubusercontent.com/goliatone/rabbithook-builder/master/conf/init.d/rhbuilder

echo "Set permissions for rhbuilder"
chmod 755 /etc/init.d/rhbuilder

echo "Registering service with update-rc.d"
sudo update-rc.d rhbuilder defaults

#echo "Starting rhbuilder boot job"
#sudo /etc/init.d/rhbuilder start
