#!/bin/bash

#Load config file!
source /usr/local/opt/rhbuilder/.rhbuilder

/usr/local/bin/rhbuilder -uri $RHBUILDER_AMQP_URL  \
          -exchange $RHBUILDER_AMQP_EXCHANGE \
          -exchange-type topic \
          -key $RHBUILDER_AMQP_TOPIC \
          -lifetime 0 \
          -jobs-path $RHBUILDER_JOBS_PATH
