#!/bin/bash
# /etc/init.d/rhbuilder

### BEGIN INIT INFO
# Provides:          rhbuilder
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start rhbuilder at boot
# Description:       This service is used start / stop rhbuilder at boot. It will also load configuration options
### END INIT INFO


case "$1" in
    start)
        echo "Starting rhbuilder"
        /usr/local/opt/rhbuilder-launcher
        ;;
    stop)
        echo "Stopping rhbuilder"
        killall rhbuilder
        ;;
    *)
        echo "Usage: /etc/init.d/rhbuilder {start|stop}"
        exit 1
        ;;
esac

exit 0
