#!/bin/bash

echo "Stopping rhbuilder service"
sudo /etc/init.d/rhbuilder stop

echo "Removing rhbuilder from update-rc.d..."
sudo update-rc.d rhbuilder remove

#rm /etc/default/rhbuilder
echo "Removing rhbuilder launcher..."
rm -f /usr/local/opt/rhbuilder/launcher

echo "Removing rhbuilder binary from /usr/local/bin/..."
rm -f /usr/local/bin/rhbuilder

echo "Removing rhbuilder from init.d..."
rm -f /etc/init.d/rhbuilder
